apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-generator
  labels:
    app: request-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-generator
  template:
    metadata:
      labels:
        app: request-generator
      annotations:
          'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
      - name: request-generator
        image: requestgenerator:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: request-generator-service
spec:
  selector:
    app: request-generator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: ExternalName
  externalName: prometheus-service.monitoring.svc.cluster.local