apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-sender-deployment
  labels:
    app: micro-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-sender
  template:
    metadata:
      labels:
        app: micro-sender
    spec:
      containers:
      - name: micro-sender
        image: microsender:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-sender-service
spec:
  selector:
    app: micro-sender
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000