---
apiVersion: v1
kind: Pod
metadata:
   name: micro-receiver
spec:
   containers:
   - name: receiver-container01
     image: microreceiver:1.0
     ports:
     - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: micro-receiver-service
  labels:
    service: micro-receiver-service
spec:
  selector:
    app: micro-receiver
  ports:
  - port: 8000
    targetPort: 8000