apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-receiver-deployment
  labels:
    app: micro-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-receiver
  template:
    metadata:
      labels:
        app: micro-receiver
    spec:
      containers:
      - name: micro-receiver
        image: microreceiver:1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: micro-receiver-service
spec:
  selector:
    app: micro-receiver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000